dist: xenial
#sudo: required
language: cpp
compiler: gcc

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get update -qq

install: 
  # C++17
  - sudo apt-get install -qq g++-6 python3.6 python3-pip
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  # cppcheck
  - sudo apt-get install -qq cppcheck
  - sudo pip3 install tensorflow==1.12 keras
script: 
  # Build and run this project
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - python3 ../python_model.py
  - ./keras2cpp
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
